//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 04:38:28 PM CET 
//


package gr.forth.ics.isl.maze.x3ml;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for example_data_infoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="example_data_infoComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="example_data_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="example_data_contact_person" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}example_data_source_record"/>
 *         &lt;element name="generator_policy_info">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="generator_link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}example_data_target_record"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "example_data_infoComplexType", propOrder = {
    "exampleDataFrom",
    "exampleDataContactPerson",
    "exampleDataSourceRecord",
    "generatorPolicyInfo",
    "exampleDataTargetRecord"
})
public class ExampleDataInfoComplexType {

    @XmlElement(name = "example_data_from", required = true)
    protected String exampleDataFrom;
    @XmlElement(name = "example_data_contact_person", required = true)
    protected String exampleDataContactPerson;
    @XmlElement(name = "example_data_source_record", required = true)
    protected ExampleDataSourceRecord exampleDataSourceRecord;
    @XmlElement(name = "generator_policy_info", required = true)
    protected ExampleDataInfoComplexType.GeneratorPolicyInfo generatorPolicyInfo;
    @XmlElement(name = "example_data_target_record", required = true)
    protected ExampleDataTargetRecord exampleDataTargetRecord;

    /**
     * Gets the value of the exampleDataFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExampleDataFrom() {
        return exampleDataFrom;
    }

    /**
     * Sets the value of the exampleDataFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExampleDataFrom(String value) {
        this.exampleDataFrom = value;
    }

    /**
     * Gets the value of the exampleDataContactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExampleDataContactPerson() {
        return exampleDataContactPerson;
    }

    /**
     * Sets the value of the exampleDataContactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExampleDataContactPerson(String value) {
        this.exampleDataContactPerson = value;
    }

    /**
     * Gets the value of the exampleDataSourceRecord property.
     * 
     * @return
     *     possible object is
     *     {@link ExampleDataSourceRecord }
     *     
     */
    public ExampleDataSourceRecord getExampleDataSourceRecord() {
        return exampleDataSourceRecord;
    }

    /**
     * Sets the value of the exampleDataSourceRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExampleDataSourceRecord }
     *     
     */
    public void setExampleDataSourceRecord(ExampleDataSourceRecord value) {
        this.exampleDataSourceRecord = value;
    }

    /**
     * Gets the value of the generatorPolicyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExampleDataInfoComplexType.GeneratorPolicyInfo }
     *     
     */
    public ExampleDataInfoComplexType.GeneratorPolicyInfo getGeneratorPolicyInfo() {
        return generatorPolicyInfo;
    }

    /**
     * Sets the value of the generatorPolicyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExampleDataInfoComplexType.GeneratorPolicyInfo }
     *     
     */
    public void setGeneratorPolicyInfo(ExampleDataInfoComplexType.GeneratorPolicyInfo value) {
        this.generatorPolicyInfo = value;
    }

    /**
     * Gets the value of the exampleDataTargetRecord property.
     * 
     * @return
     *     possible object is
     *     {@link ExampleDataTargetRecord }
     *     
     */
    public ExampleDataTargetRecord getExampleDataTargetRecord() {
        return exampleDataTargetRecord;
    }

    /**
     * Sets the value of the exampleDataTargetRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExampleDataTargetRecord }
     *     
     */
    public void setExampleDataTargetRecord(ExampleDataTargetRecord value) {
        this.exampleDataTargetRecord = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="generator_link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class GeneratorPolicyInfo {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "generator_link")
        protected String generatorLink;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the generatorLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeneratorLink() {
            return generatorLink;
        }

        /**
         * Sets the value of the generatorLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeneratorLink(String value) {
            this.generatorLink = value;
        }

    }

}
