//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 04:38:28 PM CET 
//


package gr.forth.ics.isl.maze.x3ml;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link TargetInfo }
     * 
     */
    public TargetInfo createTargetInfoComplexType() {
        return new TargetInfo();
    }

    /**
     * Create an instance of {@link TargetInfoComplexType.Namespaces }
     * 
     */
    public TargetInfo.Namespaces createTargetInfoComplexTypeNamespaces() {
        return new TargetInfo.Namespaces();
    }

    /**
     * Create an instance of {@link SourceInfo }
     * 
     */
    public SourceInfo createSourceInfoComplexType() {
        return new SourceInfo();
    }

    /**
     * Create an instance of {@link SourceInfoComplexType.Namespaces }
     * 
     */
    public SourceInfo.Namespaces createSourceInfoComplexTypeNamespaces() {
        return new SourceInfo.Namespaces();
    }

    /**
     * Create an instance of {@link ExampleDataInfoComplexType }
     * 
     */
    public ExampleDataInfoComplexType createExampleDataInfoComplexType() {
        return new ExampleDataInfoComplexType();
    }

    /**
     * Create an instance of {@link TargetSchema }
     * 
     */
    public TargetSchema createTargetSchema() {
        return new TargetSchema();
    }

    /**
     * Create an instance of {@link ExampleDataTargetRecord }
     * 
     */
    public ExampleDataTargetRecord createExampleDataTargetRecord() {
        return new ExampleDataTargetRecord();
    }

    /**
     * Create an instance of {@link ExampleDataSourceRecord }
     * 
     */
    public ExampleDataSourceRecord createExampleDataSourceRecord() {
        return new ExampleDataSourceRecord();
    }

    /**
     * Create an instance of {@link SourceSchema }
     * 
     */
    public SourceSchema createSourceSchema() {
        return new SourceSchema();
    }

    /**
     * Create an instance of {@link Info.Source }
     * 
     */
    public Info.Source createInfoSource() {
        return new Info.Source();
    }

    /**
     * Create an instance of {@link Info.Target }
     * 
     */
    public Info.Target createInfoTarget() {
        return new Info.Target();
    }

    /**
     * Create an instance of {@link MappingInfoComplexType }
     * 
     */
    public MappingInfoComplexType createMappingInfoComplexType() {
        return new MappingInfoComplexType();
    }

    /**
     * Create an instance of {@link TargetInfoComplexType.Namespaces.Namespace }
     * 
     */
    public TargetInfo.Namespaces.Namespace createTargetInfoComplexTypeNamespacesNamespace() {
        return new TargetInfo.Namespaces.Namespace();
    }

    /**
     * Create an instance of {@link SourceInfoComplexType.Namespaces.Namespace }
     * 
     */
    public SourceInfo.Namespaces.Namespace createSourceInfoComplexTypeNamespacesNamespace() {
        return new SourceInfo.Namespaces.Namespace();
    }

    /**
     * Create an instance of {@link ExampleDataInfoComplexType.GeneratorPolicyInfo }
     * 
     */
    public ExampleDataInfoComplexType.GeneratorPolicyInfo createExampleDataInfoComplexTypeGeneratorPolicyInfo() {
        return new ExampleDataInfoComplexType.GeneratorPolicyInfo();
    }

}
